#!/usr/bin/env python3
"""
SCEPTR Transcriptome Landscape Analysis.

Generates a comprehensive exploratory report from merged annotation+expression
data. Designed to characterise the expression landscape, annotation quality,
and functional composition patterns for hypothesis generation.

Features:
  1. Expression distribution & concentration (Gini, Lorenz curve)
  2. Transcriptome dominance table (top N genes, cumulative %)
  3. Annotation quality assessment (by expression level)
  4. Taxonomic distribution of DIAMOND hits
  5. Expression-rank functional composition shifts
  6. ExPlot / GO enrichment concordance (if results available)

All analyses use data already generated by upstream SCEPTR modules.

Author: James McCabe
Module: SCEPTR Landscape
"""

import os
import sys
import json
import argparse
import logging
import base64
from io import BytesIO
from datetime import datetime
from typing import Dict, List, Optional, Tuple, Any

import pandas as pd
import numpy as np

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from matplotlib.colors import LinearSegmentedColormap

logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger('sceptr.landscape')


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def fig_to_base64(fig, dpi=150):
    """Convert matplotlib figure to base64 PNG string."""
    buf = BytesIO()
    fig.savefig(buf, format='png', dpi=dpi, bbox_inches='tight', facecolor='white')
    buf.seek(0)
    b64 = base64.b64encode(buf.read()).decode('utf-8')
    plt.close(fig)
    return b64


def save_and_encode(fig, filepath, dpi=300):
    """Save figure to file AND return base64."""
    fig.savefig(filepath, dpi=dpi, bbox_inches='tight', facecolor='white')
    svg_path = filepath.replace('.png', '.svg')
    fig.savefig(svg_path, bbox_inches='tight', facecolor='white', format='svg')
    b64 = fig_to_base64(fig, dpi=150)
    return b64


# ---------------------------------------------------------------------------
# 1. Expression Distribution & Concentration
# ---------------------------------------------------------------------------

def calculate_gini(values):
    """Calculate Gini coefficient for expression concentration."""
    values = np.sort(np.array(values, dtype=float))
    n = len(values)
    if n == 0 or values.sum() == 0:
        return 0.0
    index = np.arange(1, n + 1)
    return (2 * np.sum(index * values) - (n + 1) * np.sum(values)) / (n * np.sum(values))


def expression_distribution_analysis(df, prefix):
    """Analyse expression distribution and generate Lorenz curve."""
    tpm = df['TPM'].values.copy()
    tpm = np.sort(tpm)
    total = tpm.sum()

    if total == 0:
        return {'gini': 0, 'top10_pct': 0, 'top50_pct': 0, 'top100_pct': 0,
                'median_tpm': 0, 'mean_tpm': 0, 'zero_pct': 0}, None

    n = len(tpm)
    cumulative = np.cumsum(tpm) / total
    x = np.arange(1, n + 1) / n

    gini = calculate_gini(tpm)

    # Top-gene concentration
    tpm_desc = np.sort(tpm)[::-1]
    cum_desc = np.cumsum(tpm_desc) / total
    top10_pct = cum_desc[min(9, n - 1)] * 100
    top50_pct = cum_desc[min(49, n - 1)] * 100
    top100_pct = cum_desc[min(99, n - 1)] * 100

    stats = {
        'gini': round(gini, 3),
        'top10_pct': round(top10_pct, 1),
        'top50_pct': round(top50_pct, 1),
        'top100_pct': round(top100_pct, 1),
        'median_tpm': round(float(np.median(tpm)), 2),
        'mean_tpm': round(float(np.mean(tpm)), 2),
        'zero_pct': round((tpm == 0).sum() / n * 100, 1),
        'total_genes': n,
        'expressed_genes': int((tpm > 0).sum()),
    }

    # --- Figure: Lorenz curve + TPM distribution ---
    fig, axes = plt.subplots(1, 2, figsize=(14, 5.5))

    # Lorenz curve
    ax1 = axes[0]
    ax1.fill_between(x, cumulative, alpha=0.15, color='#2d5a87')
    ax1.plot(x, cumulative, color='#2d5a87', linewidth=2, label=f'Expression (Gini = {gini:.3f})')
    ax1.plot([0, 1], [0, 1], '--', color='#999', linewidth=1, label='Perfect equality')
    ax1.set_xlabel('Cumulative fraction of genes (ranked by TPM)', fontsize=11)
    ax1.set_ylabel('Cumulative fraction of total expression', fontsize=11)
    ax1.set_title('Expression Concentration (Lorenz Curve)', fontsize=13, fontweight='bold')
    ax1.legend(fontsize=9, loc='upper left')
    ax1.set_xlim(0, 1)
    ax1.set_ylim(0, 1)

    # Annotate key percentiles
    for pct, label in [(10, 'Top 10'), (50, 'Top 50'), (100, 'Top 100')]:
        if pct <= n:
            gene_frac = pct / n
            expr_frac = cum_desc[pct - 1]
            ax1.annotate(f'{label}: {expr_frac * 100:.0f}%',
                         xy=(1 - gene_frac, 1 - (1 - expr_frac)),
                         fontsize=8, color='#e8913a', fontweight='bold')

    # TPM distribution (log scale)
    ax2 = axes[1]
    tpm_nonzero = tpm[tpm > 0]
    if len(tpm_nonzero) > 0:
        log_tpm = np.log10(tpm_nonzero)
        ax2.hist(log_tpm, bins=50, color='#2d5a87', alpha=0.7, edgecolor='white', linewidth=0.5)
        ax2.axvline(np.log10(np.median(tpm_nonzero)), color='#e8913a', linestyle='--',
                    linewidth=2, label=f'Median: {np.median(tpm_nonzero):.1f} TPM')
        ax2.set_xlabel('log₁₀(TPM)', fontsize=11)
        ax2.set_ylabel('Number of genes', fontsize=11)
        ax2.set_title('Expression Distribution', fontsize=13, fontweight='bold')
        ax2.legend(fontsize=9)

    plt.tight_layout()
    b64 = save_and_encode(fig, f"{prefix}_expression_distribution.png")

    return stats, b64


# ---------------------------------------------------------------------------
# 2. Transcriptome Dominance Table
# ---------------------------------------------------------------------------

def build_dominance_table(df, top_n=30):
    """Build top-N most expressed genes with cumulative percentage."""
    total_tpm = df['TPM'].sum()
    if total_tpm == 0:
        return pd.DataFrame()

    top = df.nlargest(top_n, 'TPM').copy()
    top['cumulative_tpm'] = top['TPM'].cumsum()
    top['pct_of_total'] = (top['TPM'] / total_tpm * 100).round(2)
    top['cumulative_pct'] = (top['cumulative_tpm'] / total_tpm * 100).round(2)
    top['rank'] = range(1, len(top) + 1)

    cols = ['rank', 'sequence_id', 'TPM', 'pct_of_total', 'cumulative_pct']
    for c in ['protein_name', 'gene_names', 'organism', 'uniprot_id']:
        if c in top.columns:
            cols.insert(3, c)

    return top[[c for c in cols if c in top.columns]]


# ---------------------------------------------------------------------------
# 3. Annotation Quality Assessment
# ---------------------------------------------------------------------------

def annotation_quality_analysis(df, prefix):
    """Assess annotation completeness across expression levels."""
    n = len(df)
    has_uniprot = df['uniprot_id'].notna() & (df['uniprot_id'].astype(str).str.strip() != '')
    has_protein_name = False
    if 'protein_name' in df.columns:
        has_protein_name = df['protein_name'].notna() & (
            df['protein_name'].astype(str).str.strip() != '') & (
            df['protein_name'].astype(str).str.lower() != 'unknown protein')

    go_cols = ['GO_Biological_Process', 'GO_Cellular_Component', 'GO_Molecular_Function']
    has_any_go = pd.Series([False] * n, index=df.index)
    go_stats = {}
    for col in go_cols:
        if col in df.columns:
            has_col = df[col].notna() & (df[col].astype(str).str.strip() != '') & (
                df[col].astype(str).str.strip() != 'nan')
            has_any_go = has_any_go | has_col
            go_stats[col] = int(has_col.sum())

    overall = {
        'total_genes': n,
        'with_diamond_hit': int(has_uniprot.sum()),
        'diamond_pct': round(has_uniprot.sum() / n * 100, 1) if n > 0 else 0,
        'with_any_go': int(has_any_go.sum()),
        'go_pct': round(has_any_go.sum() / n * 100, 1) if n > 0 else 0,
        'go_by_category': go_stats,
    }

    if isinstance(has_protein_name, pd.Series):
        overall['with_protein_name'] = int(has_protein_name.sum())

    # Annotation rate by expression decile
    df_sorted = df.sort_values('TPM', ascending=False).reset_index(drop=True)
    n_per_decile = max(1, n // 10)
    decile_stats = []
    for i in range(10):
        start = i * n_per_decile
        end = min((i + 1) * n_per_decile, n)
        subset = df_sorted.iloc[start:end]
        n_sub = len(subset)
        if n_sub == 0:
            continue

        sub_uniprot = subset['uniprot_id'].notna() & (subset['uniprot_id'].astype(str).str.strip() != '')
        sub_go = pd.Series([False] * n_sub, index=subset.index)
        for col in go_cols:
            if col in subset.columns:
                sub_go = sub_go | (subset[col].notna() & (subset[col].astype(str).str.strip() != '') &
                                   (subset[col].astype(str).str.strip() != 'nan'))

        decile_stats.append({
            'decile': i + 1,
            'label': f"{'Top' if i == 0 else ''} {(i)*10+1}-{(i+1)*10}%",
            'n_genes': n_sub,
            'diamond_pct': round(sub_uniprot.sum() / n_sub * 100, 1),
            'go_pct': round(sub_go.sum() / n_sub * 100, 1),
            'median_tpm': round(float(subset['TPM'].median()), 2),
        })

    # --- Figure: annotation rate by expression level ---
    if decile_stats:
        fig, ax = plt.subplots(figsize=(10, 5))
        deciles = [d['decile'] for d in decile_stats]
        diamond_rates = [d['diamond_pct'] for d in decile_stats]
        go_rates = [d['go_pct'] for d in decile_stats]

        x = np.arange(len(deciles))
        width = 0.35
        ax.bar(x - width / 2, diamond_rates, width, label='DIAMOND hit', color='#2d5a87', alpha=0.8)
        ax.bar(x + width / 2, go_rates, width, label='GO annotation', color='#e8913a', alpha=0.8)
        ax.set_xlabel('Expression decile (1 = highest)', fontsize=11)
        ax.set_ylabel('Annotation rate (%)', fontsize=11)
        ax.set_title('Annotation Completeness by Expression Level', fontsize=13, fontweight='bold')
        ax.set_xticks(x)
        ax.set_xticklabels([f"D{d}" for d in deciles], fontsize=9)
        ax.legend(fontsize=10)
        ax.set_ylim(0, 105)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        ax.grid(axis='y', alpha=0.3)

        plt.tight_layout()
        b64 = save_and_encode(fig, f"{prefix}_annotation_quality.png")
    else:
        b64 = None

    return overall, decile_stats, b64


# ---------------------------------------------------------------------------
# 4. Taxonomic Distribution
# ---------------------------------------------------------------------------

def taxonomic_distribution(df, prefix, top_n=20):
    """Analyse taxonomic distribution of DIAMOND best hits."""
    if 'organism' not in df.columns:
        return {}, None

    org = df[df['organism'].notna() & (df['organism'].astype(str).str.strip() != '') &
             (df['organism'].astype(str).str.lower() != 'unknown organism')]

    if len(org) == 0:
        return {}, None

    # Count organisms
    org_counts = org['organism'].value_counts()
    total_hits = len(org)

    top_orgs = org_counts.head(top_n)
    other_count = org_counts.iloc[top_n:].sum() if len(org_counts) > top_n else 0

    stats = {
        'total_hits': total_hits,
        'unique_organisms': len(org_counts),
        'top_organism': org_counts.index[0],
        'top_organism_pct': round(org_counts.iloc[0] / total_hits * 100, 1),
        'top_5_pct': round(org_counts.head(5).sum() / total_hits * 100, 1),
    }

    # --- Figure: horizontal bar chart of top organisms ---
    fig, ax = plt.subplots(figsize=(10, max(5, top_n * 0.3)))

    y_labels = list(top_orgs.index)
    y_values = list(top_orgs.values)
    if other_count > 0:
        y_labels.append(f'Other ({len(org_counts) - top_n} species)')
        y_values.append(other_count)

    y_labels = y_labels[::-1]
    y_values = y_values[::-1]
    pcts = [v / total_hits * 100 for v in y_values]

    colors = ['#2d5a87'] * len(y_values)
    if other_count > 0:
        colors[0] = '#bbb'

    bars = ax.barh(range(len(y_labels)), pcts, color=colors, alpha=0.8, edgecolor='white')
    ax.set_yticks(range(len(y_labels)))
    ax.set_yticklabels(y_labels, fontsize=9)
    ax.set_xlabel('Percentage of DIAMOND hits', fontsize=11)
    ax.set_title('Taxonomic Distribution of Best DIAMOND Hits', fontsize=13, fontweight='bold')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    for bar, pct in zip(bars, pcts):
        if pct > 2:
            ax.text(bar.get_width() + 0.3, bar.get_y() + bar.get_height() / 2,
                    f'{pct:.1f}%', va='center', fontsize=8, color='#555')

    plt.tight_layout()
    b64 = save_and_encode(fig, f"{prefix}_taxonomic_distribution.png")

    return stats, b64


# ---------------------------------------------------------------------------
# 5. Expression-Rank Functional Shifts
# ---------------------------------------------------------------------------

def _normalize_landscape_categories(categories):
    """Extract keyword lists from either legacy or v2 category format."""
    normalised = {}
    for cat, val in categories.items():
        if isinstance(val, dict) and 'keywords' in val:
            normalised[cat] = val['keywords']
        elif isinstance(val, list):
            normalised[cat] = val
        else:
            normalised[cat] = []
    return normalised


def functional_shift_analysis(df, categories, prefix):
    """Show how functional composition changes across expression rank."""
    import re

    if not categories:
        return None

    # Normalise v2 format to plain keyword lists
    categories = _normalize_landscape_categories(categories)

    df_sorted = df.sort_values('TPM', ascending=False).reset_index(drop=True)
    n = len(df_sorted)

    # Identify annotation fields
    ann_fields = [c for c in df.columns if c in [
        'protein_name', 'Protein_Name', 'GO_Biological_Process',
        'GO_Molecular_Function', 'GO_Cellular_Component',
        'annotation', 'description', 'product']]

    if not ann_fields:
        return None

    # Sliding window: 200-gene windows, step 50
    window_size = min(200, n // 5) if n > 100 else n
    step = max(window_size // 4, 1)

    window_centres = []
    category_fractions = {cat: [] for cat in categories}

    for start in range(0, n - window_size + 1, step):
        end = start + window_size
        window = df_sorted.iloc[start:end]
        centre_rank = (start + end) / 2
        window_centres.append(centre_rank)

        # Count category matches in this window
        window_text = []
        for _, row in window.iterrows():
            parts = []
            for f in ann_fields:
                v = row.get(f)
                if pd.notna(v):
                    parts.append(str(v).lower())
            window_text.append(' '.join(parts))

        for cat, keywords in categories.items():
            match_count = 0
            for text in window_text:
                for kw in keywords:
                    if re.search(r'\b' + re.escape(kw.lower()) + r'\b', text):
                        match_count += 1
                        break
            category_fractions[cat].append(match_count / window_size * 100)

    if not window_centres:
        return None

    # --- Figure: stacked area chart ---
    fig, ax = plt.subplots(figsize=(14, 6.5))

    # Use a qualitative colormap
    n_cats = len(categories)
    cmap = plt.cm.get_cmap('tab20', n_cats)
    colors = [cmap(i) for i in range(n_cats)]

    cat_names = list(categories.keys())
    # Remove Uncharacterised from stacking (plot separately)
    main_cats = [c for c in cat_names if 'uncharacteri' not in c.lower()]
    unchar_cat = [c for c in cat_names if 'uncharacteri' in c.lower()]

    y_stack = np.array([category_fractions[c] for c in main_cats])
    ax.stackplot(window_centres, y_stack, labels=main_cats, colors=colors[:len(main_cats)], alpha=0.8)

    # Overlay uncharacterised as a dashed line
    for uc in unchar_cat:
        ax.plot(window_centres, category_fractions[uc], '--', color='#999',
                linewidth=2, label=uc)

    ax.set_xlabel('Expression rank (1 = highest)', fontsize=11)
    ax.set_ylabel('Functional composition (% of window)', fontsize=11)
    ax.set_title('Functional Composition Across Expression Gradient', fontsize=13, fontweight='bold')
    ax.legend(loc='center left', bbox_to_anchor=(1.02, 0.5), fontsize=8, frameon=False)
    ax.set_xlim(window_centres[0], window_centres[-1])
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()
    b64 = save_and_encode(fig, f"{prefix}_functional_shifts.png")

    return b64


# ---------------------------------------------------------------------------
# 6. Concordance Analysis (ExPlot vs GO Enrichment)
# ---------------------------------------------------------------------------

def concordance_analysis(explot_results_file, go_results_file, prefix):
    """Compare ExPlot keyword enrichment with topGO results."""
    if not explot_results_file or not os.path.exists(explot_results_file):
        return None, None
    if not go_results_file or not os.path.exists(go_results_file):
        return None, None

    try:
        go_df = pd.read_csv(go_results_file, sep='\t')
        with open(explot_results_file) as f:
            explot_data = json.load(f)
    except Exception as e:
        logger.warning(f"Could not load concordance data: {e}")
        return None, None

    # Extract significant GO terms per tier
    go_sig = {}
    if 'Term' in go_df.columns and 'Tier' in go_df.columns:
        for tier in go_df['Tier'].unique():
            tier_data = go_df[(go_df['Tier'] == tier) & (go_df['Fold_Enrichment'] >= 1.5)]
            if 'FDR' in go_df.columns:
                tier_data = tier_data[tier_data['FDR'] <= 0.05]
            go_sig[f"top_{tier}"] = set(tier_data['Term'].str.lower())

    # Extract significant ExPlot categories per tier
    explot_sig = {}
    for tier_name, tier_data in explot_data.items():
        if isinstance(tier_data, dict) and 'enrichment' in tier_data:
            sig_cats = set()
            for cat, stats in tier_data['enrichment'].items():
                if stats.get('significant', False) and stats.get('fold_change', 0) >= 1.5:
                    sig_cats.add(cat.lower())
            explot_sig[tier_name] = sig_cats

    summary = {
        'go_tiers_analysed': len(go_sig),
        'explot_tiers_analysed': len(explot_sig),
        'go_total_significant': sum(len(v) for v in go_sig.values()),
        'explot_total_significant': sum(len(v) for v in explot_sig.values()),
    }

    return summary, None


# ---------------------------------------------------------------------------
# HTML Report Generation
# ---------------------------------------------------------------------------

def generate_landscape_report(
    expr_stats, expr_fig,
    dominance_df,
    ann_stats, ann_deciles, ann_fig,
    tax_stats, tax_fig,
    shift_fig,
    concordance_stats,
    prefix, total_genes,
):
    """Generate the transcriptome landscape HTML dashboard."""

    # --- Dominance table HTML ---
    dom_html = ""
    if dominance_df is not None and len(dominance_df) > 0:
        header = "<tr>"
        for col in dominance_df.columns:
            nice = col.replace('_', ' ').title()
            if col == 'TPM':
                nice = 'TPM'
            elif col == 'pct_of_total':
                nice = '% Total'
            elif col == 'cumulative_pct':
                nice = 'Cumul. %'
            header += f"<th>{nice}</th>"
        header += "</tr>"

        rows = ""
        for _, row in dominance_df.iterrows():
            rows += "<tr>"
            for col in dominance_df.columns:
                val = row[col]
                if col == 'TPM':
                    rows += f"<td><strong>{val:,.1f}</strong></td>"
                elif col in ('pct_of_total', 'cumulative_pct'):
                    rows += f"<td>{val:.1f}%</td>"
                elif col == 'protein_name':
                    name = str(val)[:60] + ('...' if len(str(val)) > 60 else '')
                    rows += f"<td>{name}</td>"
                else:
                    rows += f"<td>{val}</td>"
            rows += "</tr>"

        dom_html = f"""
        <div class="section">
            <h2>Transcriptome Dominance</h2>
            <p>The most highly expressed genes and their cumulative contribution to total expression.
            This reveals what the organism is investing its transcriptional resources in.</p>
            <div style="overflow-x:auto;">
            <table><thead>{header}</thead><tbody>{rows}</tbody></table>
            </div>
        </div>"""

    # --- Annotation decile table ---
    ann_table = ""
    if ann_deciles:
        ann_rows = ""
        for d in ann_deciles:
            ann_rows += f"""<tr>
                <td>D{d['decile']}</td>
                <td>{d['n_genes']:,}</td>
                <td>{d['median_tpm']:.1f}</td>
                <td>{d['diamond_pct']:.1f}%</td>
                <td>{d['go_pct']:.1f}%</td>
            </tr>"""
        ann_table = f"""
            <h3>Annotation Rate by Expression Decile</h3>
            <table>
                <thead><tr><th>Decile</th><th>Genes</th><th>Median TPM</th>
                    <th>DIAMOND Hit</th><th>GO Annotated</th></tr></thead>
                <tbody>{ann_rows}</tbody>
            </table>"""

    # --- Build figures ---
    def fig_block(b64, caption, fig_num):
        if not b64:
            return "", fig_num
        html = f"""
        <div class="fig-container">
            <img src="data:image/png;base64,{b64}" alt="{caption}">
            <p class="fig-caption">Figure {fig_num}: {caption}</p>
        </div>"""
        return html, fig_num + 1

    fig_num = 1
    expr_fig_html, fig_num = fig_block(expr_fig, "Expression distribution and concentration (Lorenz curve)", fig_num)
    ann_fig_html, fig_num = fig_block(ann_fig, "Annotation completeness by expression level", fig_num)
    tax_fig_html, fig_num = fig_block(tax_fig, "Taxonomic distribution of best DIAMOND hits", fig_num)
    shift_fig_html, fig_num = fig_block(shift_fig, "Functional composition across expression gradient", fig_num)

    # --- Gini interpretation ---
    gini = expr_stats.get('gini', 0)
    if gini > 0.85:
        gini_desc = "Highly concentrated - a small number of genes dominate expression. Common in specialised cells or organisms under stress."
    elif gini > 0.7:
        gini_desc = "Moderately concentrated - typical for differentiated tissues with active translation/metabolism."
    elif gini > 0.5:
        gini_desc = "Moderate distribution - relatively diverse transcriptional activity."
    else:
        gini_desc = "Broadly distributed - many genes contribute to total expression."

    # --- Assemble ---
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SCEPTR Transcriptome Landscape Report</title>
    <style>
:root {{
    --primary: #2d5a87; --primary-light: #4a8bc2; --primary-dark: #1d3d5c;
    --accent: #e8913a; --bg: #f0f2f5; --card: #ffffff;
    --text: #2c3e50; --text-light: #5a6c7d; --border: #e0e4e8;
}}
* {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{
    font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
    line-height: 1.6; color: var(--text); max-width: 1300px;
    margin: 0 auto; padding: 24px; background: var(--bg);
}}
.header {{
    background: linear-gradient(135deg, #1a6b54, #124d3c);
    color: white; padding: 36px 40px; border-radius: 12px;
    margin-bottom: 28px; position: relative; overflow: hidden;
}}
.header::after {{
    content: ''; position: absolute; top: -40%; right: -10%;
    width: 300px; height: 300px; border-radius: 50%;
    background: rgba(255,255,255,0.06);
}}
.header h1 {{ font-size: 1.9em; font-weight: 700; margin-bottom: 6px; position: relative; z-index: 1; }}
.header .subtitle {{ opacity: 0.85; font-size: 1.05em; position: relative; z-index: 1; }}
.header .meta {{ opacity: 0.65; font-size: 0.85em; margin-top: 10px; position: relative; z-index: 1; }}
.section {{
    background: var(--card); padding: 28px 32px; margin-bottom: 24px;
    border-radius: 10px; box-shadow: 0 1px 6px rgba(0,0,0,0.06);
}}
.section h2 {{
    color: var(--primary); font-size: 1.35em; font-weight: 700;
    border-bottom: 2px solid var(--primary-light); padding-bottom: 10px; margin-bottom: 20px;
}}
.section h3 {{ color: var(--text); font-size: 1.1em; margin: 24px 0 12px 0; }}
.section p {{ margin-bottom: 12px; }}
.stats-grid {{
    display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr));
    gap: 16px; margin: 16px 0;
}}
.stat-card {{
    background: var(--bg); padding: 18px 16px; border-radius: 8px;
    text-align: center; border-left: 4px solid var(--primary); transition: transform 0.15s;
}}
.stat-card:hover {{ transform: translateY(-2px); }}
.stat-card.accent {{ border-left-color: var(--accent); }}
.stat-card .label {{
    font-size: 0.78em; text-transform: uppercase; letter-spacing: 0.5px;
    color: var(--text-light); font-weight: 600;
}}
.stat-card .value {{ font-size: 1.8em; font-weight: 700; color: var(--text); margin: 6px 0 2px 0; }}
.stat-card .detail {{ font-size: 0.82em; color: var(--text-light); }}
table {{ width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 0.88em; }}
th, td {{ padding: 10px 14px; text-align: left; border-bottom: 1px solid var(--border); }}
th {{
    background: var(--primary); color: white; font-weight: 600;
    font-size: 0.85em; text-transform: uppercase; letter-spacing: 0.3px;
}}
tr:hover {{ background: #f8fafb; }}
.fig-container {{ text-align: center; margin: 24px 0; }}
.fig-container img {{ max-width: 100%; height: auto; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }}
.fig-caption {{ color: var(--text-light); font-size: 0.88em; font-style: italic; margin-top: 8px; }}
.methods-box {{
    background: #f8fafb; padding: 20px 24px; border-radius: 8px;
    border-left: 4px solid var(--accent); font-size: 0.9em; line-height: 1.7; color: var(--text-light);
}}
.methods-box p {{ margin-bottom: 10px; }}
.methods-box strong {{ color: var(--text); }}
.footer {{ text-align: center; padding: 20px; color: var(--text-light); font-size: 0.82em; }}
    </style>
</head>
<body>

<div class="header">
    <h1>SCEPTR Transcriptome Landscape Report</h1>
    <div class="subtitle">Exploratory characterisation of expression patterns, annotation quality, and functional composition</div>
    <div class="meta">Generated {datetime.now().strftime('%Y-%m-%d %H:%M')} &middot; SCEPTR v1.0.0</div>
</div>

<div class="section">
    <h2>Expression Landscape</h2>
    <div class="stats-grid">
        <div class="stat-card">
            <div class="label">Total Genes</div>
            <div class="value">{expr_stats.get('total_genes', total_genes):,}</div>
        </div>
        <div class="stat-card">
            <div class="label">Expressed (TPM &gt; 0)</div>
            <div class="value">{expr_stats.get('expressed_genes', 0):,}</div>
            <div class="detail">{100 - expr_stats.get('zero_pct', 0):.0f}% of total</div>
        </div>
        <div class="stat-card accent">
            <div class="label">Gini Coefficient</div>
            <div class="value">{expr_stats.get('gini', 0):.3f}</div>
            <div class="detail">Expression concentration</div>
        </div>
        <div class="stat-card accent">
            <div class="label">Top 10 Genes</div>
            <div class="value">{expr_stats.get('top10_pct', 0):.0f}%</div>
            <div class="detail">of total expression</div>
        </div>
        <div class="stat-card">
            <div class="label">Top 50 Genes</div>
            <div class="value">{expr_stats.get('top50_pct', 0):.0f}%</div>
            <div class="detail">of total expression</div>
        </div>
        <div class="stat-card">
            <div class="label">Top 100 Genes</div>
            <div class="value">{expr_stats.get('top100_pct', 0):.0f}%</div>
            <div class="detail">of total expression</div>
        </div>
    </div>
    <div class="methods-box">
        <p><strong>Gini coefficient = {expr_stats.get('gini', 0):.3f}:</strong> {gini_desc}</p>
        <p>Median TPM: {expr_stats.get('median_tpm', 0):.1f} &middot;
           Mean TPM: {expr_stats.get('mean_tpm', 0):.1f}</p>
    </div>
    {expr_fig_html}
</div>

{dom_html}

<div class="section">
    <h2>Annotation Quality</h2>
    <p>How well-annotated are the expressed genes? Bias in annotation completeness across
    expression levels can affect enrichment results - highly expressed genes are typically
    better annotated, which may inflate enrichment signals in top expression tiers.</p>
    <div class="stats-grid">
        <div class="stat-card">
            <div class="label">DIAMOND Hits</div>
            <div class="value">{ann_stats.get('diamond_pct', 0):.0f}%</div>
            <div class="detail">{ann_stats.get('with_diamond_hit', 0):,} / {ann_stats.get('total_genes', 0):,}</div>
        </div>
        <div class="stat-card accent">
            <div class="label">GO Annotated</div>
            <div class="value">{ann_stats.get('go_pct', 0):.0f}%</div>
            <div class="detail">{ann_stats.get('with_any_go', 0):,} genes</div>
        </div>
    </div>
    {ann_fig_html}
    {ann_table}
</div>

<div class="section">
    <h2>Taxonomic Distribution</h2>
    <p>Species distribution of best DIAMOND hits reveals phylogenetic context - which
    reference organisms are closest to the study species and whose literature is most
    relevant for biological interpretation. Unexpected taxa may indicate contamination.</p>
    {'<div class="stats-grid"><div class="stat-card"><div class="label">Unique Species</div><div class="value">' + str(tax_stats.get("unique_organisms", 0)) + '</div></div><div class="stat-card accent"><div class="label">Top Hit Species</div><div class="value" style="font-size:1.1em">' + str(tax_stats.get("top_organism", "N/A"))[:30] + '</div><div class="detail">' + str(tax_stats.get("top_organism_pct", 0)) + '% of hits</div></div><div class="stat-card"><div class="label">Top 5 Species</div><div class="value">' + str(tax_stats.get("top_5_pct", 0)) + '%</div><div class="detail">of all hits</div></div></div>' if tax_stats else '<p style="color:var(--text-light)">No taxonomic data available (organism column not found).</p>'}
    {tax_fig_html}
</div>

<div class="section">
    <h2>Functional Composition Shifts</h2>
    <p>How does functional composition change across the expression gradient? This reveals
    expression-dependent biology - which functional programmes dominate at the top of the
    transcriptome versus the middle and bottom. Transitions between zones often highlight
    the most biologically interesting features of the sample.</p>
    {shift_fig_html if shift_fig_html else '<p style="color:var(--text-light)">No functional categories provided for shift analysis.</p>'}
</div>

<div class="section">
    <h2>Interpretation Guide</h2>
    <div class="methods-box">
        <p><strong>Expression concentration:</strong> A high Gini coefficient (&gt;0.85) means
        a few genes dominate the transcriptome - look at the dominance table to see what they
        are. This is expected for parasites (surface antigens), stressed cells (chaperones),
        or actively dividing cells (ribosomal proteins).</p>

        <p><strong>Annotation bias:</strong> If the top expression decile has much higher
        annotation rates than lower deciles, enrichment analyses may be partially driven by
        differential annotation rather than true biological enrichment. This is particularly
        common in non-model organisms.</p>

        <p><strong>Taxonomic spread:</strong> A tight taxonomic distribution (top species &gt;50%
        of hits) indicates good reference data for your organism. A diffuse distribution or
        unexpected taxa may indicate novel biology, contamination, or phylogenetic isolation.</p>

        <p><strong>Functional shifts:</strong> The stacked area chart shows functional
        composition as a sliding window across expression ranks. Key patterns to look for:
        translation/ribosome dominance at the top (nearly universal), metabolic enrichment
        in the middle ranks, and uncharacterised gene accumulation at low expression
        (common in non-model organisms).</p>
    </div>
</div>

<div class="footer">
    SCEPTR v1.0.0 &middot; Transcriptome Landscape Analysis
    &middot; {datetime.now().strftime('%Y-%m-%d')}
</div>

</body>
</html>"""

    html_path = f"{prefix}_landscape_report.html"
    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(html)
    logger.info(f"Generated landscape report: {html_path}")
    return html_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description='SCEPTR Transcriptome Landscape Analysis')
    parser.add_argument('integrated_results', help='Merged annotation+expression TSV')
    parser.add_argument('--prefix', default='sceptr', help='Output file prefix')
    parser.add_argument('--categories', default=None,
                        help='Functional categories JSON (for shift analysis)')
    parser.add_argument('--explot_results', default=None,
                        help='ExPlot results JSON (for concordance)')
    parser.add_argument('--go_results', default=None,
                        help='GO enrichment results TSV (for concordance)')
    parser.add_argument('--top_genes', type=int, default=30,
                        help='Number of genes in dominance table')
    parser.add_argument('--top_taxa', type=int, default=20,
                        help='Number of taxa to show')
    parser.add_argument('--outdir', default='.',
                        help='Output directory (default: current directory)')
    args = parser.parse_args()

    logger.info("SCEPTR Transcriptome Landscape Analysis")
    logger.info(f"  Input: {args.integrated_results}")

    # Set up output directory structure
    fig_dir = os.path.join(args.outdir, 'figures')
    os.makedirs(fig_dir, exist_ok=True)
    fig_prefix = os.path.join(fig_dir, args.prefix)
    data_prefix = os.path.join(args.outdir, args.prefix)

    # Load data
    try:
        df = pd.read_csv(args.integrated_results, sep='\t')
    except Exception:
        df = pd.read_csv(args.integrated_results, sep=',')
    logger.info(f"Loaded {len(df)} genes")

    if 'TPM' not in df.columns:
        candidates = [c for c in df.columns if c.lower() in ['tpm', 'expression', 'fpkm']]
        if candidates:
            df['TPM'] = df[candidates[0]]
        else:
            logger.error("No TPM column found")
            sys.exit(1)

    df = df.sort_values('TPM', ascending=False).reset_index(drop=True)

    # 1. Expression distribution
    logger.info("Analysing expression distribution...")
    expr_stats, expr_fig = expression_distribution_analysis(df, fig_prefix)
    logger.info(f"  Gini: {expr_stats['gini']}, Top 10: {expr_stats['top10_pct']}%")

    # 2. Dominance table
    logger.info("Building dominance table...")
    dominance_df = build_dominance_table(df, args.top_genes)

    # 3. Annotation quality
    logger.info("Assessing annotation quality...")
    ann_stats, ann_deciles, ann_fig = annotation_quality_analysis(df, fig_prefix)
    logger.info(f"  DIAMOND: {ann_stats['diamond_pct']}%, GO: {ann_stats['go_pct']}%")

    # 4. Taxonomic distribution
    logger.info("Analysing taxonomic distribution...")
    tax_stats, tax_fig = taxonomic_distribution(df, fig_prefix, args.top_taxa)
    if tax_stats:
        logger.info(f"  Top: {tax_stats.get('top_organism', 'N/A')} ({tax_stats.get('top_organism_pct', 0)}%)")

    # 5. Functional shifts
    shift_fig = None
    categories = None
    if args.categories:
        try:
            with open(args.categories) as f:
                categories = json.load(f)
            logger.info(f"Loaded {len(categories)} categories for shift analysis")
            shift_fig = functional_shift_analysis(df, categories, fig_prefix)
        except Exception as e:
            logger.warning(f"Could not load categories: {e}")

    # 6. Concordance
    concordance_stats = None
    if args.explot_results and args.go_results:
        logger.info("Computing ExPlot/GO concordance...")
        concordance_stats, _ = concordance_analysis(args.explot_results, args.go_results, fig_prefix)

    # Generate report
    logger.info("Generating landscape report...")
    report = generate_landscape_report(
        expr_stats, expr_fig,
        dominance_df,
        ann_stats, ann_deciles, ann_fig,
        tax_stats, tax_fig,
        shift_fig,
        concordance_stats,
        data_prefix, len(df))

    # Save stats as JSON
    stats_out = {
        'expression': expr_stats,
        'annotation': ann_stats,
        'taxonomy': tax_stats,
    }
    with open(f"{data_prefix}_landscape_stats.json", 'w') as f:
        json.dump(stats_out, f, indent=2, default=str)

    logger.info("Landscape analysis complete!")


if __name__ == "__main__":
    main()
